const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1200,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await page.route('https://art.test/',r=>r.fulfill({contentType:'text/html',body:'<div id="campaignDashboard"></div>'}));await page.goto('https://art.test/');await page.addStyleTag({path:'site/vendor/bootstrap.min.css'});await page.addStyleTag({path:'site/art-atelier.css'});await page.addStyleTag({path:'site/realm-layout.css'});await page.addScriptTag({path:'site/map-art.js'});await page.addScriptTag({path:'site/art-atelier.js'});
await page.evaluate(()=>{window.saved=null;window.config={records:[{id:4,title:'Moon sword',content:{category:'item'}}],save:async(id,blob)=>{window.saved={id,type:blob.type,size:blob.size};}};ArtAtelier.setActive(true,1,1,config);});
const canvas=page.locator('#aaCanvas'),bounds=await canvas.boundingBox();await page.locator('#aaTool').selectOption('rect');await page.locator('#aaFilled').check();await page.mouse.move(bounds.x+bounds.width/2-70,bounds.y+bounds.height/2-70);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+70,bounds.y+bounds.height/2+70);await page.mouse.up();assert.equal(await page.locator('#aaArt>g').count(),1);
await page.locator('#aaCopy').click();assert.equal(await page.locator('#aaArt>g').count(),2);await page.locator('#aaUndo').click();assert.equal(await page.locator('#aaArt>g').count(),1);await page.locator('#aaRedo').click();assert.equal(await page.locator('#aaArt>g').count(),2);
await page.getByText('Layers & files',{exact:true}).click();await page.locator('#aaLayers button').first().click();await page.locator('#aaAngle').fill('45');await page.locator('#aaAngle').press('Tab');assert.match(await page.locator('#aaArt>g').last().getAttribute('transform'),/rotate\(45\)/);
await page.locator('#aaApply').click();console.log(await page.locator("#aaStatus").textContent());await page.waitForFunction(()=>window.saved,{},{timeout:5000});assert.equal((await page.evaluate(()=>saved)).type,'image/png');assert.ok((await page.evaluate(()=>saved)).size>100);
await page.evaluate(()=>{ArtAtelier.setActive(false);ArtAtelier.setActive(true,2,1,config);});assert.equal(await page.locator('#aaArt>g').count(),0);await page.evaluate(()=>ArtAtelier.setActive(true,1,1,config));assert.equal(await page.locator('#aaArt>g').count(),2);
const download=page.waitForEvent('download');await page.locator('#aaDownload').click();assert.equal((await download).suggestedFilename(),'campaign-artwork.png');await page.getByText('Map stamps & canvas guides',{exact:true}).click();await page.locator('#aaStampSearch').fill('chest');await page.locator('#aaStamps button').first().click();await page.waitForFunction(()=>document.querySelectorAll('#aaArt>g').length===3,{},{timeout:5000});assert.equal(await page.locator('#aaArt image').count(),1);
await page.locator('#aaLayers input[type=checkbox]').nth(1).check();assert.equal(await page.locator('#aaDelete').isDisabled(),true);await page.locator('#aaLayers input[type=checkbox]').first().check();assert.equal(await page.locator('#aaArt>g').last().evaluate(e=>e.style.display),'none');await page.locator('#aaUndo').click();assert.equal(await page.locator('#aaArt>g').last().evaluate(e=>e.style.display),'');
const projectDownload=page.waitForEvent('download');await page.locator('#aaProjectSave').click();const project=await projectDownload;const projectPath=await project.path();await page.locator('#aaClear').click();assert.equal(await page.locator('#aaArt>g').count(),0);await page.locator('#aaProjectOpen').setInputFiles(projectPath);await page.waitForFunction(()=>document.querySelectorAll('#aaArt>g').length===3,{},{timeout:5000});
await page.getByText('Layers & files',{exact:true}).click();await page.getByText('Map stamps & canvas guides',{exact:true}).click();await page.locator('#aaFullscreen').click();assert.equal(await page.evaluate(()=>document.fullscreenElement?.id),'artAtelier');await page.screenshot({path:'tests/art-atelier.png'});assert.deepEqual(errors,[]);console.log('Drawing, fill, duplicate, history, rotation, PNG, apply, campaign drafts and fullscreen passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

