const {chromium}=require(process.env.TABLETOP_PLAYWRIGHT||'playwright');
const fs=require('fs'),assert=require('node:assert/strict');const root=require('path').resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({...(process.env.TABLETOP_CHROME?{executablePath:process.env.TABLETOP_CHROME}:{}),headless:true});try{
const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log(e.stack);});
await page.route('https://art.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="campaignDashboard"></div>'}));await page.goto('https://art.test/');
const html=fs.readFileSync(root+'/site/index.html','utf8');for(const m of html.matchAll(/<link rel="stylesheet" href="([^"]+)"/g))await page.addStyleTag({content:fs.readFileSync(root+'/site/'+m[1].split('?')[0],'utf8')});
await page.evaluate(()=>{window.MapImagePicker={create:()=>({setArtwork(){}})};window.saved=[];window.config={archive:async(title,description,blob)=>saved.push({title,description,size:blob.size})};});
await page.addScriptTag({path:root+'/site/art-atelier.js'});await page.evaluate(()=>ArtAtelier.setActive(true,1,1,config));
await page.locator('.aa-generation summary').click();await page.locator('#aaTransparent').uncheck();await page.locator('.aa-generation summary').click();
const image=fs.readFileSync(root+'/tests/local-art-cat.png');let calls=[],uploads=0,mode='success';
await page.route('**/api/uploads/*',r=>r.fulfill({contentType:'image/png',body:image}));await page.route('**/api/upload',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({image_id:++uploads+50})}));
await page.route('**/art/design',async r=>{calls.push(r.request().postDataJSON());const n=calls.length;if(mode==='slow')await new Promise(resolve=>setTimeout(resolve,1400));if(mode==='mixed'&&n%2===0)return r.fulfill({status:503,contentType:'application/json',body:'{"error":"Test generation failed"}'});await r.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({event:'image',image_id:41})+'\n'+JSON.stringify({event:'done',result_kind:'image',description:'Generated cat'})+'\n'}).catch(()=>{});});
const done=()=>page.waitForFunction(()=>!document.querySelector('#aaGenerate').disabled);
await page.locator('#aaPrompt').fill('a wandering cat');await page.locator('#aaStyle').selectOption('Painted anime illustration');await page.locator('#aaGenerate').click();await done();
assert.equal(calls.length,4);assert.ok(calls.every(c=>JSON.stringify(c)===JSON.stringify(calls[0])));assert.match(calls[0].prompt,/Painted anime/);assert.equal(await page.locator('.aa-result-preview img').count(),4);assert.equal(await page.locator('#aaArt image').count(),0);
await page.getByRole('button',{name:'Keep in archive',exact:true}).first().click();assert.equal(await page.evaluate(()=>saved.length),1);
await page.getByRole('button',{name:'Open in drawing studio',exact:true}).first().click();assert.equal(await page.locator('#aaArt image').count(),1);await page.locator('#aaUndo').click();assert.equal(await page.locator('#aaArt image').count(),0);await page.locator('#aaRedo').click();
await page.locator('.aa-generation summary').click();await page.locator('#aaAppend').check();await page.locator('#aaBatchSize').selectOption('2');await page.locator('#aaGenerate').click();await done();assert.equal(uploads,1);assert.equal(calls.length,6);assert.equal(calls[4].source_image_id,calls[5].source_image_id);assert.equal(await page.locator('#aaArt image').count(),1);await page.locator('#aaAppend').uncheck();await page.locator('.aa-generation summary').click();
await page.locator('.aa-reference-options>summary').click();await page.locator('#aaReferenceImport').setInputFiles([{name:'cat-one.png',mimeType:'image/png',buffer:image},{name:'cat-two.png',mimeType:'image/png',buffer:image}]);await page.waitForFunction(()=>document.querySelectorAll('.aa-reference-tile').length===2);assert.equal(await page.locator('.aa-reference-detail').count(),0);await page.locator('.aa-reference-tile').first().click();await page.locator('.aa-reference-detail textarea').fill('Use these colors');await page.locator('.aa-reference-tile').nth(1).click();assert.equal(await page.locator('.aa-reference-detail textarea').inputValue(),'');await page.locator('.aa-reference-tile').first().click();assert.equal(await page.locator('.aa-reference-detail textarea').inputValue(),'Use these colors');
mode='mixed';await page.locator('#aaGenerate').click();await done();assert.equal(await page.locator('.aa-failed').count(),1);assert.equal(await page.locator('.aa-result-preview img').count(),7);assert.equal(calls[6].image_references.length,2);assert.equal(calls[6].image_references[0].note,'Use these colors');
mode='slow';await page.locator('#aaBatchSize').selectOption('6');await page.locator('#aaGenerate').click();await page.waitForTimeout(100);await page.locator('#aaStopAI').click();const stopped=calls.length;await page.waitForTimeout(1500);assert.equal(calls.length,stopped);assert.equal(await page.locator('.aa-pending').count(),0);assert.equal(await page.locator('#aaArt image').count(),1);
for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),theme+' horizontal overflow');assert.ok((await page.locator('.aa-reference-tile').first().boundingBox()).width<120);await page.screenshot({path:__dirname+'/atelier-mobile-'+theme+'.png',fullPage:true});}
await page.setViewportSize({width:1440,height:1000});await page.locator('#aaFullscreen').click();assert.equal(await page.evaluate(()=>document.fullscreenElement?.id),'artAtelier');await page.screenshot({path:__dirname+'/atelier-fullscreen.png'});
await page.evaluate(()=>document.exitFullscreen());await page.locator('#aaDrawing').evaluate(e=>e.open=true);await page.locator('#aaTool').selectOption('rect');await page.locator('#aaCanvas').scrollIntoViewIfNeeded();const canvas=await page.locator('#aaCanvas').boundingBox();await page.mouse.move(canvas.x+canvas.width*.45,canvas.y+canvas.height*.45);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.55,canvas.y+canvas.height*.55);await page.mouse.up();assert.equal(await page.locator('#aaArt>g').count(),2);await page.locator('#aaUndo').click();assert.equal(await page.locator('#aaArt>g').count(),1);
await page.locator('.aa-generation').evaluate(e=>e.open=true);await page.locator('#aaRenderer').selectOption('vector');assert.equal(await page.locator('#aaBatchSize').isDisabled(),true);await page.route('**/art/design',r=>r.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({event:'layer',node:{type:'rect',x:256,y:256,w:100,h:100,scale:1,angle:0,ink:'#000000',fill:'#ffffff',width:1}})+'\n'+JSON.stringify({event:'done',result_kind:'sketch'})+'\n'}));
await page.evaluate(()=>ArtAtelier.setActive(true,2,1,config));await page.locator('#aaPrompt').fill('a rectangle');await page.locator('#aaGenerate').click();await done();assert.equal(await page.locator('#aaArt rect').count(),1);assert.equal(await page.locator('.aa-result').count(),0);assert.equal(await page.locator('.aa-reference-tile').count(),0);assert.deepEqual(errors,[]);console.log('PASS: batch snapshots, independent failures, archive keep, editor undo, shared edit source, compact references, stop, campaign isolation, mobile themes and fullscreen.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
