const {chromium}=require(process.env.TABLETOP_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
  const browser=await chromium.launch({executablePath:process.env.TABLETOP_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});
  const base='https://127.0.0.1:8766';
  const auth=await context.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});assert.equal(auth.status(),200);
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Page error:',e.message);});
  // Capture completed modal transitions, rather than translucent opening frames.
  const screenshot=page.screenshot.bind(page);
  page.screenshot=options=>screenshot({animations:'disabled',...options});
  const items=async()=>(await (await context.request.get(base+'/api/work')).json()).items;
  const modal=page.locator('#workModal');const characterName='Elara QA '+Date.now();
  async function closeDetail(){await page.locator('#recordDetailModal [data-bs-dismiss]').first().click();await page.locator('#recordDetailModal').waitFor({state:'hidden'});}
  async function openArchive(type){await page.locator('#realmMenuButton').click();await page.locator('#realmSidebar [data-record-type="'+type+'"]').click();}
  await page.goto(base);await page.locator('#newCampaignButton').waitFor({state:'visible'});
  await page.locator('#newCampaignButton').click();await modal.waitFor({state:'visible'});
  await modal.locator('[name=title]').fill('QA tabletop '+Date.now());
  await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});
  let records=await items();const campaign=records.find(r=>r.content.category==='campaign');assert(campaign);
  assert.equal(records.filter(r=>r.content.campaign_id===campaign.id&&r.content.reference_only).length,122);
  await page.screenshot({path:path.join(out,'desktop-library.png')});
  await page.locator('#newSavedCharacterButton').click();await modal.waitFor({state:'visible'});
  await modal.locator('[name=title]').fill(characterName);
  await modal.locator('[name=character_class]').fill('Wizard');
  await modal.locator('[name=constitution]').fill('14');await modal.locator('#ttStartHP').click();
  assert.equal(await modal.locator('[name=hp_max]').inputValue(),'8');assert.equal(await modal.locator('[name=hit_die]').inputValue(),'d6');
  await modal.locator('[name=character_level]').fill('5');await modal.locator('[name=dexterity]').fill('16');await modal.locator('[name=wisdom]').fill('14');
  await modal.locator('[name=tt_skill_stealth]').selectOption('2');assert.equal(await modal.locator('[data-tt-roll=skill_stealth]').textContent(),'+9');
  await modal.locator('[name=tt_skill_perception]').selectOption('1');await modal.locator('#ttDerive').click();
  assert.equal(await modal.locator('[name=initiative]').inputValue(),'3');assert.equal(await modal.locator('[name=passive_perception]').inputValue(),'15');
  await modal.locator('[name=hp_max]').fill('30');await modal.locator('[name=hp_current]').fill('20');await modal.locator('[name=hp_temporary]').fill('5');
  await modal.locator('[name=tt_hp_amount]').fill('8');await modal.locator('[data-tt-hp=damage]').click();assert.equal(await modal.locator('[name=hp_current]').inputValue(),'17');assert.equal(await modal.locator('[name=hp_temporary]').inputValue(),'0');
  await modal.locator('[name=tt_slot_1_max]').fill('4');await modal.locator('[name=tt_slot_1_remaining]').fill('3');
  await modal.locator('[name=tt_concentration]').fill('Bless · 4 rounds');
  await modal.locator('[name=tt_skill_stealth]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'desktop-character.png')});
  await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});
  records=await items();const character=records.find(r=>r.title===characterName);assert.equal(character.content.tabletop.skill_stealth,2);assert.equal(character.content.hp_current,17);assert.equal(character.content.tabletop.slot_1_remaining,3);
  await page.locator('.saved-character-card').filter({hasText:characterName}).first().click();await modal.waitFor({state:'visible'});assert.equal(await modal.locator('[name=tt_concentration]').inputValue(),'Bless · 4 rounds');
  await modal.locator('[name=tt_slot_1_remaining]').fill('5');await modal.locator('button[type=submit]').click();assert.match(await page.locator('#workError').textContent(),/cannot exceed/);await modal.locator('[name=tt_slot_1_remaining]').fill('3');
  await page.setViewportSize({width:390,height:844});await modal.locator('[name=tt_skill_stealth]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'mobile-character.png')});
  assert(await modal.evaluate(el=>el.scrollWidth<=el.clientWidth+2));
  await modal.locator('button[data-bs-dismiss]').last().click();await modal.waitFor({state:'hidden'});await page.setViewportSize({width:1440,height:1000});
  await page.locator('.campaign-row').filter({hasText:campaign.title}).click();
  await openArchive('item');await page.locator('#recordSearch').fill('Potion of Healing');
  await page.locator('#workList .work-card').filter({hasText:'Potion of Healing'}).first().locator('h3').click();await page.screenshot({path:path.join(out,'item-detail.png')});await page.locator('#recordDetailModal').waitFor({state:'visible'});
  assert.match(await page.locator('#detailSharedNotesText').textContent(),/Bonus action/);
  await page.locator('#detailCopyReference').click();await modal.waitFor({state:'visible'});
  assert.equal(await modal.locator('[name=reference_only]').isChecked(),false);
  await modal.locator('[name=title]').fill('Elara’s healing potion');await modal.locator('[name=quantity]').fill('0');
  await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});
  records=await items();const copy=records.find(r=>r.title==='Elara’s healing potion');assert.equal(copy.content.quantity,0);assert.equal(copy.content.reference_only,false);assert(copy.content.source_url);assert.equal(copy.content.tabletop.weight,0.5);
  assert.equal(records.filter(r=>r.content.campaign_id===campaign.id&&r.content.reference_only).length,122);
  await page.locator('#recordSearch').fill('');await openArchive('encounter');await page.locator('#addSectionRecord').click();await modal.waitFor({state:'visible'});
  await modal.locator('[name=title]').fill('Chapel encounter');await modal.locator('#ttAddCombatant').click();await modal.locator('#ttAddCombatant').click();
  await modal.locator('[data-key=name]').nth(0).fill('Elara');await modal.locator('[data-key=initiative]').nth(0).fill('18');await modal.locator('[data-key=name]').nth(1).fill('Guard');await modal.locator('[data-key=initiative]').nth(1).fill('7');await modal.locator('#ttSortInitiative').click();
  await modal.locator('#ttNextTurn').click();assert.match(await modal.locator('#ttTurnStatus').textContent(),/Guard/);await modal.locator('#ttNextTurn').click();assert.equal(await modal.locator('[name=tt_round]').inputValue(),'2');
  await page.screenshot({path:path.join(out,'encounter.png')});await modal.locator('button[type=submit]').click();await modal.waitFor({state:'hidden'});
  await openArchive('spell');await page.locator('#recordSearch').fill('Cure Wounds');await page.locator('#workList .work-card').first().click();await page.locator('#recordDetailModal').waitFor({state:'visible'});assert.match(await page.locator('#detailSharedNotesText').textContent(),/2d8/);await page.screenshot({path:path.join(out,'spell-reference.png')});await closeDetail();
  await page.locator('#realmMenuButton').click();await page.locator('#tabletopDiceButton').click();await page.locator('#diceModal').waitFor({state:'visible'});
  await page.locator('#diceExpression').fill('1d20 + 5');await page.locator('#diceMode').selectOption('advantage');await page.locator('#diceForm button[type=submit]').click();assert(Number(await page.locator('#diceResult').textContent())>=6);
  await page.locator('#diceExpression').fill('2d6');await page.locator('#diceForm button[type=submit]').click();assert.match(await page.locator('#diceError').textContent(),/one d20/);
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(out,'dark-dice.png')});
  assert.deepEqual(errors,[]);console.log('Browser checks passed: new campaign defaults, character math/save/reload, slot validation, mobile layout, reference copying, fractional weight, zero quantity, encounter order and spell/dice views.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
