require('./python-path.cjs');
/* Isolated application test: never writes to the user's campaign database. */
const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),base='https://127.0.0.1:8779';
const python='C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const server=spawn(python,['-u','-c',`import tempfile,pathlib,sys
import storage,server
server.ThreadingHTTPServer.request_queue_size=128
server.Handler.protocol_version='HTTP/1.1'
temp=tempfile.TemporaryDirectory(prefix='map-environment-')
storage.DB_PATH=pathlib.Path(temp.name)/'site.db'
storage.UPLOAD_DIR=pathlib.Path(temp.name)/'uploads'
storage.initialize()
uid=storage.create_user('EnvironmentQA',None,'Environment-QA-12345')
storage.create_work(uid,'Environment QA',{'category':'campaign','initial_map_kind':'2d'})
sys.argv=['server.py','--port','8779']
server.main()`],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
(async()=>{let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});
 for(let i=0;i<80;i++){try{const response=await context.request.get(base,{timeout:1000});if(response.ok())break;}catch{}await new Promise(r=>setTimeout(r,250));if(i===79)throw Error(output);}
 const login=await context.request.post(base+'/api/login',{data:{username:'EnvironmentQA',password:'Environment-QA-12345'}});assert.ok(login.ok(),await login.text());
 const campaign=(await(await context.request.get(base+'/api/work')).json()).items.find(r=>r.title==='Environment QA');
 const listing=await(await context.request.get(base+'/api/campaign/'+campaign.id+'/maps')).json(),url=base+'/api/campaign/'+campaign.id+'/maps/'+listing.active_map_id;
 const nodes=[{id:'floor',type:'grass',x:-550,y:-320,w:1100,h:640},...['mossy_boulder','rock_outcrop','standing_stone','driftwood','fern_patch','cattails','tide_pool','ice_crystal','stalagmite','fallen_leaves','glowing_mushrooms','brazier','lantern','candle_cluster','rune_stone','timber_fence'].map((type,i)=>({id:type,type,x:-450+i%6*155,y:-230+Math.floor(i/6)*170,w:100,h:100,label:type.replaceAll('_',' '),effects:false}))];
 const state={nodes,scene:{time:'Evening',weather:'Clear',temperature:'Mild'},canvas:{grid:false,background:'empty'}};
 let saved=await context.request.put(url,{data:{revision:0,state}});assert.ok(saved.ok(),await saved.text());
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.stack);});page.on('console',msg=>{if(msg.type()==='error'){errors.push(msg.text());console.error('CONSOLE',msg.text());}});
 await page.goto(base);await page.locator('.campaign-row').filter({hasText:'Environment QA'}).click();await page.locator('#map2Canvas').waitFor({state:'visible'});
 await page.waitForFunction(()=>document.querySelector('#mapPointLighting')?.dataset.lightCount==='5');
 await page.locator('[data-map-mode="edit"]').click();await page.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();
 await page.waitForFunction(()=>document.querySelector('#map2Canvas').dataset.materialRenderer==='pbr');
 await page.waitForTimeout(1500);
 assert.ok(await page.locator('[data-node="mossy_boulder"] [data-map-sprite]').count());
 await page.screenshot({path:path.join(__dirname,'artifacts/environment-parts.png')});
 const crops=await page.evaluate(()=>({cage:MapSprites.crop('cage'),pit:MapSprites.crop('spike_pit')}));assert.ok(crops.cage[1]+crops.cage[3]<crops.pit[1],'Cage cannot bleed into the pit crop');
 const gallery=await context.newPage();await gallery.route(base+'/map-art-gallery',route=>route.fulfill({contentType:'text/html',body:`<base href="${base}/"><style>body{margin:0;padding:20px;background:#343d32;color:#eee;font:14px system-ui;display:grid;grid-template-columns:repeat(9,140px);gap:12px}.part{text-align:center;background:#46513f;padding:8px;border-radius:8px}svg{width:124px;height:124px;display:block}</style>`}));await gallery.goto(base+'/map-art-gallery');
 await gallery.evaluate(()=>{window.MapArt={extend(){}};window.MapPartProfiles={noShadow:new Set()};});
 for(const file of ['map-sprite-bounds.js','map-item-props.js','map-sprites.js'])await gallery.addScriptTag({path:path.join(root,'site',file)});
 await gallery.evaluate(async()=>{const ns='http://www.w3.org/2000/svg',el=(tag,attrs,parent)=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);parent?.append(n);return n;};for(const type of MapSprites.types){const box=document.createElement('div');box.className='part';const svg=el('svg',{viewBox:'0 0 100 100'},box);MapSprites.render({type,w:100,h:100},svg,el);box.append(type.replaceAll('_',' '));document.body.append(box);}await Promise.all(MapSprites.types.map(t=>MapSprites.load(t)));});
 await gallery.waitForFunction(()=>[...document.querySelectorAll('[data-map-sprite]')].every(n=>n.hasAttribute('href')));await gallery.screenshot({path:path.join(__dirname,'artifacts/map-art-gallery.png'),fullPage:true});const exported=await gallery.evaluate(async()=>{const entries=await Promise.all(MapSprites.types.map(async type=>[type,await MapSprites.tile(type)]));return Object.fromEntries(entries);});const fs=require('node:fs');fs.mkdirSync(path.join(root,'site/assets/map-art/items'),{recursive:true});for(const [type,url] of Object.entries(exported))fs.writeFileSync(path.join(root,'site/assets/map-art/items',type+'.png'),Buffer.from(url.split(',')[1],'base64'));await gallery.close();
 // Existing and new light sources share the same editor and persisted fields.
 await page.locator('#map2Canvas [data-node="lantern"]').click();assert.ok(await page.locator('#map2LightOptions').isVisible());
 await page.locator('#map2LightRadius').fill('270');await page.locator('#map2LightRadius').press('Tab');
 await page.locator('[data-map2-property="light_color"]').fill('#99ddff');await page.waitForTimeout(700);
 let loaded=(await(await context.request.get(url)).json()).state;assert.equal(loaded.nodes.find(n=>n.id==='lantern').light_radius,270);
 assert.equal(loaded.nodes.find(n=>n.id==='lantern').light_color,'#99ddff');
 await page.locator('#map2Canvas [data-node="mossy_boulder"]').click();assert.ok(await page.locator('#map2HeightOptions').isVisible());
 await page.locator('[data-map2-property="height_scale"]').fill('2');await page.locator('[data-map2-property="height_scale"]').press('Tab');await page.waitForTimeout(700);
 loaded=(await(await context.request.get(url)).json()).state;assert.equal(loaded.nodes.find(n=>n.id==='mossy_boulder').height_scale,2);
 // Verify material frequency independently of the object's stretch transform.
 const tiling=await page.evaluate(()=>{const ns='http://www.w3.org/2000/svg',host=document.createElementNS(ns,'g');document.querySelector('#map2Canvas').append(host);const render=(w,h)=>{host.replaceChildren();MapArt.render({id:'test-stretch',type:'bridge',w,h},host);return host.querySelector('pattern').getAttribute('height');};const result=[render(100,100),render(400,50)];host.remove();return result;});
 assert.deepEqual(tiling,['12','12'],'Stretched bridge repeats its plank pitch');
 const heights=await page.evaluate(()=>new Promise(resolve=>{const n={type:'mossy_boulder',w:100,h:100};const done=()=>{const r=MapSilhouettes.request(n,done,128);if(r?.resolution===128)resolve([...new Set(r.map(v=>v[4]))]);};done();}));assert.ok(heights.length>=4,'Heightmap must have multiple elevations');
 const shadowPixels=await page.evaluate(async()=>{
  const wait=()=>new Promise(r=>setTimeout(r,300)),sum=()=>{const c=document.querySelector('#mapPointLighting'),data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let total=0;for(let i=3;i<data.length;i+=4)total+=data[i];return total;};
  const n={id:'height-test',type:'mossy_boulder',x:-50,y:-50,w:100,h:100};MapLighting.update({time:'Evening',weather:'Clear'});
  const values=[];for(const height_scale of [0,.5,2]){MapLighting.geometry([{...n,height_scale}],{});await wait();values.push(sum());}
  const edge=MapVisibility.viewport(document.querySelector('#map2Canvas'),0);MapLighting.geometry([{...n,x:edge.minX-120,height_scale:2}],{});await wait();values.push(sum());return values;
 });assert.equal(shadowPixels[0],0,'Zero height casts no shadow');assert.ok(shadowPixels[2]>shadowPixels[1]*1.5,'Height changes actual cast-shadow pixels');assert.ok(shadowPixels[3]>0,'Off-screen parts still cast visible shadows');
 const lightShadows=await page.evaluate(async()=>{MapLighting.geometry(Object.keys(MapPartProfiles.lights).map((type,i)=>({id:type,type,x:i*40,y:0,w:40,h:40,light_intensity:0})),{});await new Promise(r=>setTimeout(r,200));return document.querySelector('#mapPointLighting').dataset.totalObjects;});assert.equal(lightShadows,'0','No light-emitting part enters the shadow geometry');
 const motion=await page.evaluate(async()=>{
  const svg=document.querySelector('#map2Canvas'),g=document.createElementNS(svg.namespaceURI,'g');svg.append(g);
  MapArt.render({id:'moving-test',type:'water',x:0,y:0,w:800,h:80,baseW:100,baseH:100,shape:'stroke',points:[[0,50],[100,50]],brush:30,softness:0},g);
  MapMaterials.view(svg,{});const moving=svg.querySelector('#mapTexture-water [data-texture-flow]');for(let i=0;i<100&&moving.dataset.frames!=='8';i++)await new Promise(r=>setTimeout(r,100));const first=moving.lastElementChild.getAttribute('opacity');await new Promise(r=>setTimeout(r,150));
  const result={first,last:moving.lastElementChild.getAttribute('opacity'),drift:moving.getAttribute('transform'),copies:moving.querySelectorAll('image,use').length,transform:g.querySelector('[href="#mapTexture-water"]').getAttribute('patternTransform'),overlay:g.querySelectorAll('.map-water-motion,[data-animated-texture]').length};
  g.replaceChildren();MapArt.render({id:'still-test',type:'water',x:0,y:0,w:100,h:100,effects:false},g);result.still=g.querySelector('rect').getAttribute('fill');g.remove();return result;
 });assert.notEqual(motion.first,motion.last,'Actual lit ripple frames animate');assert.equal(motion.drift,null,'Water ripples without directional drift');assert.equal(motion.copies,2,'Shared ripple images blend without per-part animation');assert.ok(motion.transform.startsWith('scale(0.125 1.25)'));assert.equal(motion.overlay,0);assert.equal(motion.still,'url(#mapTexture-water-still)');
 // The test scene is local-only after persistence checks. Distant parts remain saved,
 // but do not create SVG nodes, shadow silhouettes or active light buffers.
 const culling=await page.evaluate(()=>{const nodes=[{id:'near',type:'mossy_boulder',x:0,y:0,w:80,h:80},...Array.from({length:1000},(_,i)=>({id:'distant'+i,type:i%2?'rock':'lantern',x:10000+i*110,y:10000,w:80,h:80}))];Map2D.configure({edit:true,dm:true,nodes,players:[],canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});return nodes.length;});
 await page.waitForTimeout(600);assert.equal(culling,1001);assert.ok(Number(await page.locator('#map2Canvas').getAttribute('data-visible-parts'))<5);assert.equal(await page.locator('#mapPointLighting').getAttribute('data-visible-lights'),'0');
 // Exercise actual wheel zoom so viewport drawing and quality updates both run.
 const before=Number(await page.locator('#map2Canvas').getAttribute('data-material-resolution'));
 const box=await page.locator('#map2Canvas').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
 const navigation=await page.evaluate(async()=>{const svg=document.querySelector('#map2Canvas'),c=document.querySelector('#mapPointLighting'),r=svg.getBoundingClientRect(),count=Number(c.dataset.renderCount),gaps=[];let last=performance.now();for(let i=0;i<10;i++){svg.dispatchEvent(new WheelEvent('wheel',{deltaY:-100,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));await new Promise(resolve=>requestAnimationFrame(resolve));const now=performance.now();gaps.push(now-last);last=now;}return {redraws:Number(c.dataset.renderCount)-count,maxFrameMs:Math.max(...gaps),view:svg.getAttribute('viewBox')};});
 assert.ok(navigation.redraws<=1,'Navigation defers expensive shadow rendering');console.log('Navigation:',navigation);
 await page.waitForFunction(()=>Number(document.querySelector('#map2Canvas').dataset.materialResolution)>=1024,{timeout:30000});
 assert.ok(Number(await page.locator('#mapPointLighting').getAttribute('data-shadow-resolution'))>64);assert.ok(before<=1024);
 await page.screenshot({path:path.join(__dirname,'artifacts/environment-zoom.png')});
 assert.deepEqual(errors,[]);console.log('PASS 16 persisted parts, textured props, animated image tiling, lamp controls, height-based shadow pixels, off-screen casters, zoom detail, deferred redraws and culling 1,000 distant parts');
 console.log(await page.locator('#mapPointLighting').evaluate(c=>({...c.dataset})));
 // Relief must respond to the direction of an actual point light, not an overlay.
 const relief=await page.evaluate(async()=>{const n={id:'relief',type:'mossy_boulder',x:-50,y:-50,w:100,h:100};MapLighting.update({time:'Night'});const samples=[];for(const x of [-100,100]){MapLighting.geometry([n,{id:'lamp',type:'lantern',x:x-10,y:-10,w:20,h:20,light_radius:300,light_intensity:1,fire_light:false}],{});const tile=await MapSurfaceLighting.bitmap(n),data=tile.canvas.getContext('2d').getImageData(0,0,256,256).data;let left=0,right=0;for(let y=60;y<190;y++)for(let x=50;x<206;x++){const i=(y*256+x)*4;if(data[i+3]<100)continue;const l=data[i]+data[i+1]+data[i+2];if(x<128)left+=l;else right+=l;}samples.push(left-right);}return samples;});assert.ok(Math.abs(relief[0]-relief[1])>10000,'Moving a light must change surface shading');console.log('Relief direction samples:',relief);
 // Dense visible brushes reproduce the reported worst case, unlike distant culling.
 await page.evaluate(()=>{const nodes=Array.from({length:600},(_,i)=>({id:'dense'+i,type:i%2?'oak_tree':'pine_tree',x:-175+i%30*12,y:-105+Math.floor(i/30)*11,w:22,h:22,rotation:i*23%360}));MapLighting.update({time:'Evening'});Map2D.configure({edit:true,dm:true,nodes,players:[],canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});});
 await page.waitForFunction(()=>[...document.querySelectorAll('[data-ambience-batch]')].reduce((n,i)=>n+Number(i.dataset.visibleInstances),0)>=600);await page.waitForTimeout(600);
 const dense=await page.locator('#mapPointLighting').evaluate(c=>({...c.dataset}));assert.ok(Number(dense.visibleObjects)>=500);assert.ok(Number(dense.renderMs)<250,'Dense canopy shadow refresh must not stall for a second');
 const stable=await page.evaluate(async()=>{const svg=document.querySelector('#map2Canvas'),r=svg.getBoundingClientRect(),images=[...svg.querySelectorAll('[data-ambience-batch]')],gaps=[];let t=performance.now();for(let i=0;i<12;i++){svg.dispatchEvent(new WheelEvent('wheel',{deltaY:i%2?100:-100,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));await new Promise(requestAnimationFrame);gaps.push(performance.now()-t);t=performance.now();if(images.some(img=>!img.isConnected||!img.hasAttribute('href')))return {stable:false};}return {stable:true,maxFrameMs:Math.max(...gaps)};});assert.ok(stable.stable,'Zoom must retain current brush images until replacements decode');console.log('600 visible trees:',dense.renderMs,'ms; navigation:',stable);await page.screenshot({path:path.join(__dirname,'artifacts/dense-canopy.png')});
 // Nested folders lock descendants and flatten their display without losing sources.
 await page.evaluate(()=>{window.folderState=null;Map2D.configure({edit:true,dm:true,folders:[{id:'parent',name:'Room'},{id:'child',name:'Table props',parent_id:'parent'}],nodes:[{id:'table',type:'table',x:-80,y:-50,w:160,h:100,folder_id:'parent'},{id:'book',type:'book_red',x:-30,y:-10,w:30,h:40,folder_id:'child'}],players:[],canvas:{grid:false},onChange:(nodes,folders)=>window.folderState={nodes,folders},onCanvasChange:()=>{}});});
 assert.equal(await page.locator('[data-folder-id="parent"] [data-folder-id="child"]').count(),1);await page.getByRole('button',{name:'Lock folder Room',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-folder-batch="parent"]')?.dataset.batchedParts==='2');assert.equal(await page.locator('#map2Canvas [data-node]').count(),1);assert.equal(await page.evaluate(()=>folderState.nodes.length),2);await page.getByRole('button',{name:'Unlock folder Room',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#map2Canvas [data-node]').length===2);console.log('PASS nested folder lock, single-image rendering and unlock preserves parts');
 // Exercise the normal image upload path using a single cropped prop.
 await page.evaluate(()=>{const d=document.querySelector('.map-image-library');d.open=true;});await page.waitForFunction(()=>document.querySelector('.map-image-library button[title="book red"]'));await page.evaluate(()=>document.querySelector('.map-image-library button[title="book red"]').click());await page.waitForFunction(()=>Number(document.querySelector('#workForm [name=image_id]').value)>0);const itemImage=await page.locator('#workForm [name=image_id]').inputValue();assert.ok((await context.request.get(base+'/api/uploads/'+itemImage)).ok());console.log('PASS individual artwork can be selected as item image');
 // Joining two actual mouse-painted strokes must retain one connected layer.
 await page.evaluate(()=>{window.paintState=[];Map2D.configure({edit:true,dm:true,nodes:[],players:[],canvas:{grid:false},onChange:nodes=>window.paintState=nodes,onCanvasChange:()=>{}});document.querySelector('[data-map2-tool="grass"]').click();document.querySelector('#map2DrawMode').value='brush';document.querySelector('#map2BrushSize').value='35';document.querySelector('#map2Snap').checked=false;document.querySelector('#map2Reverse').checked=false;});
 const brushBox=await page.locator('#map2Canvas').boundingBox(),cx=brushBox.x+brushBox.width/2,cy=brushBox.y+brushBox.height/2;for(const [a,b] of [[-100,0],[-10,100]]){await page.mouse.move(cx+a,cy);await page.mouse.down();await page.mouse.move(cx+b,cy,{steps:8});await page.mouse.up();}assert.equal(await page.evaluate(()=>paintState.length),1);assert.equal(await page.evaluate(()=>paintState[0].strokes.length),2);await page.screenshot({path:path.join(__dirname,'artifacts/connected-paint.png')});console.log('PASS mouse-painted strokes connect');assert.deepEqual(errors,[]);
 const catalogProps=await page.evaluate(()=>Object.entries(MapItemProps.byTitle).map(([title,type])=>({title,type,has:MapSprites.has(type),url:StarterArt.url({title,content:{category:'item'}})})));assert.equal(catalogProps.length,77);for(const p of catalogProps){assert.ok(p.has);assert.equal(p.url,'/assets/map-art/items/'+p.type+'.png');assert.ok(require('node:fs').existsSync(path.join(root,'site',p.url)));}console.log('PASS all 77 catalog items have matching props and reusable images');
 // Long zoom-out inside a room must never expose the edge of a stale light canvas.
 await page.evaluate(()=>{MapLighting.update({time:'Night',weather:'Clear'});Map2D.configure({edit:true,dm:true,nodes:[{id:'room',type:'building',x:-2200,y:-1800,w:4400,h:3600,floor_texture:'wood',wall_texture:'stone',wall_width:12},{id:'lamp',type:'lantern',x:0,y:0,w:60,h:60,light_radius:600,light_intensity:1,fire_light:false}],players:[],canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});});await page.waitForTimeout(500);
 const coverage=await page.evaluate(async()=>{const svg=document.querySelector('#map2Canvas'),canvas=document.querySelector('#mapPointLighting'),r=svg.getBoundingClientRect();let missing=0,previews=0,maxFrame=0,t=performance.now();for(let i=0;i<24;i++){svg.dispatchEvent(new WheelEvent('wheel',{deltaY:100,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));await new Promise(requestAnimationFrame);const b=canvas.getBoundingClientRect();if(b.left>r.left+1||b.top>r.top+1||b.right<r.right-1||b.bottom<r.bottom-1)missing++;if(canvas.dataset.preview==='true')previews++;const now=performance.now();maxFrame=Math.max(maxFrame,now-t);t=now;}return {missing,previews,maxFrame};});assert.equal(coverage.missing,0,'Lighting must cover the whole view throughout zoom-out');console.log('Indoor zoom-out coverage:',coverage);await page.waitForTimeout(250);await page.screenshot({path:path.join(__dirname,'artifacts/indoor-zoom-out.png')});assert.deepEqual(errors,[]);
 // Outdoor props retain their image nodes through a wide zoom change and a pan.
 await page.evaluate(()=>{MapLighting.update({time:'Evening',weather:'Clear'});Map2D.configure({edit:true,dm:true,nodes:Array.from({length:300},(_,i)=>({id:'outdoor'+i,type:['table','barrel','mossy_boulder'][i%3],x:-1700+i%30*120,y:-600+Math.floor(i/30)*120,w:70,h:70})),players:[],canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});});await page.waitForTimeout(500);
 const outdoor=await page.evaluate(async()=>{const svg=document.querySelector('#map2Canvas'),images=[...svg.querySelectorAll('[data-map-sprite]')],r=svg.getBoundingClientRect(),light=document.querySelector('#mapPointLighting');let detached=0,uncovered=0;for(let i=0;i<28;i++){svg.dispatchEvent(new WheelEvent('wheel',{deltaY:i<14?-100:100,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));await new Promise(requestAnimationFrame);if(images.some(img=>!img.isConnected))detached++;const b=light.getBoundingClientRect();if(b.left>r.left+1||b.top>r.top+1||b.right<r.right-1||b.bottom<r.bottom-1)uncovered++;}return {count:images.length,detached,uncovered};});assert.equal(outdoor.count,300);assert.equal(outdoor.detached,0);assert.equal(outdoor.uncovered,0);console.log('Outdoor zoom stability:',outdoor);await page.mouse.move(cx,cy);await page.mouse.down({button:'middle'});await page.mouse.move(cx+300,cy+120,{steps:10});await page.mouse.up({button:'middle'});assert.equal(await page.locator('#map2Canvas [data-map-sprite]').count(),300);await page.waitForTimeout(250);await page.screenshot({path:path.join(__dirname,'artifacts/outdoor-zoom.png')});assert.deepEqual(errors,[]);
 const mobile=await browser.newContext({ignoreHTTPSErrors:true,isMobile:true,hasTouch:true,viewport:{width:844,height:390}});await mobile.request.post(base+'/api/login',{data:{username:'EnvironmentQA',password:'Environment-QA-12345'}});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base);await mp.locator('.campaign-row').filter({hasText:'Environment QA'}).click();await mp.locator('#map2Canvas').waitFor({state:'visible'});await mp.waitForTimeout(600);assert.ok(await mp.locator('#mapPointLighting').evaluate(c=>Math.max(c.width,c.height)<=1024));assert.deepEqual(errors,[]);console.log('PASS mobile artwork and bounded lighting');
 }finally{await browser?.close();server.kill();}})().catch(error=>{console.error(error);console.error(output.slice(-2000));process.exitCode=1;});
