require('./python-path.cjs');
/* Isolated application test: never writes to the user's campaign database. */
const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),base='https://127.0.0.1:17902';
const python='C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const server=spawn(python,['-u','-c',`import tempfile,pathlib,sys
import storage,server
server.ThreadingHTTPServer.request_queue_size=128
server.Handler.protocol_version='HTTP/1.1'
temp=tempfile.TemporaryDirectory(prefix='map-part-cards-')
storage.DB_PATH=pathlib.Path(temp.name)/'site.db'
storage.UPLOAD_DIR=pathlib.Path(temp.name)/'uploads'
storage.initialize()
uid=storage.create_user('PartCardsQA',None,'Environment-QA-12345')
storage.create_work(uid,'Part Cards QA',{'category':'campaign','initial_map_kind':'2d'})
sys.argv=['server.py','--port','17902']
server.main()`],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
(async()=>{let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});
 for(let i=0;i<80;i++){try{const response=await context.request.get(base,{timeout:1000});if(response.ok())break;}catch{}await new Promise(r=>setTimeout(r,250));if(i===79)throw Error(output);}
 const login=await context.request.post(base+'/api/login',{data:{username:'PartCardsQA',password:'Environment-QA-12345'}});assert.ok(login.ok(),await login.text());
 const campaign=(await(await context.request.get(base+'/api/work')).json()).items.find(r=>r.title==='Part Cards QA');



 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='warning'&&m.text().includes('canvas light'))errors.push(m.text());});
 await page.goto(base);await page.locator('.campaign-row').filter({hasText:'Part Cards QA'}).click();await page.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();await page.evaluate(()=>Map2D.sync=()=>{});await page.waitForTimeout(300);
 const setup=async(count,casters=true)=>page.evaluate(({count,casters})=>{const nodes=Array.from({length:count},(_,i)=>({id:'fire'+i,type:'lantern',x:-250+i%6*90,y:-150+Math.floor(i/6)*90,w:24,h:24,light_radius:220,light_color:i%2?'#ff2200':'#2233ff',light_intensity:1,fire_light:true,fire_wave:1,fire_flicker:1}));if(casters)nodes.push(...Array.from({length:16},(_,i)=>({id:'prop'+i,type:i%2?'barrel':'chair',x:-180+i%4*90,y:-90+Math.floor(i/4)*70,w:35,h:35})));Map2D.configure({nodes,players:[],edit:false,dm:true,canvas:{background:'wood',grid:false},onChange:()=>{},onCanvasChange:()=>{}});MapLighting.update({time:'Night'});},{count,casters});
 for(const count of [1,8,24]){await setup(count);await page.waitForTimeout(2200);await page.waitForFunction(()=>document.querySelector('#mapPointLighting').dataset.lightRenderer==='gpu',null,{timeout:10000});const result=await page.evaluate(async()=>{const c=document.querySelector('#mapPointLighting'),start=Number(c.dataset.renderCount),masks=Number(c.dataset.maskBuilds),gaps=[],begin=performance.now();let last=begin,readbacks=0;const read=CanvasRenderingContext2D.prototype.getImageData;CanvasRenderingContext2D.prototype.getImageData=function(...a){readbacks++;return read.apply(this,a);};try{while(performance.now()-begin<1100){await new Promise(requestAnimationFrame);const now=performance.now();gaps.push(now-last);last=now;}}finally{CanvasRenderingContext2D.prototype.getImageData=read;}return {renderMs:Number(c.dataset.renderMs),updates:Number(c.dataset.renderCount)-start,maskRebuilds:Number(c.dataset.maskBuilds)-masks,readbacks,averageFrame:gaps.reduce((a,b)=>a+b)/gaps.length,maxFrame:Math.max(...gaps),size:[c.width,c.height]};});console.log(count+' shadow-casting fires:',result);assert.equal(result.maskRebuilds,0,'Flicker cannot rebuild shadow masks');assert.equal(result.readbacks,0,'No per-frame CPU pixel readback');assert.ok(result.updates>=20,'Fire animation updates smoothly');assert.ok(result.size[0]>1000,'More lights must not collapse lighting resolution');assert.ok(result.averageFrame<40,'Many fire lights must keep the map responsive');}
 // Equal red and blue lights overlap smoothly, independently of insertion order.
 const blends=await page.evaluate(async()=>{const settings={sun_shadow_length:0},wait=()=>new Promise(r=>setTimeout(r,160)),sample=x=>{const c=document.querySelector('#mapPointLighting'),r=c.getBoundingClientRect(),m=document.querySelector('#map2Canvas').getScreenCTM(),px=Math.round((m.a*x+m.e-r.left)*c.width/r.width),py=Math.round((m.f-r.top)*c.height/r.height);return [...c.getContext('2d').getImageData(px,py,1,1).data];};const lights=[{id:'red',type:'point_light',x:-240,y:-200,w:400,h:400,color:'#ff0000',light_softness:1},{id:'blue',type:'point_light',x:-160,y:-200,w:400,h:400,color:'#0000ff',light_softness:1}];MapLighting.geometry(lights,settings);MapLighting.update({time:'Day'});await wait();const center=sample(0),left=sample(-30),right=sample(30),seam=[sample(-2),sample(2)];MapLighting.geometry(lights.slice().reverse(),settings);await wait();const reverse=sample(0);return {center,left,right,seam,reverse};});console.log('Color overlap:',blends);assert.ok(blends.center[0]>140&&blends.center[2]>140&&blends.center[1]<15,'Overlap is visibly purple');assert.ok(blends.center[3]>100,'Colored light has a stronger visible tint');assert.ok(blends.left[0]>blends.right[0]&&blends.left[2]<blends.right[2]);assert.ok(blends.seam[0].every((v,i)=>Math.abs(v-blends.seam[1][i])<15),'No abrupt seam where one light becomes stronger');assert.ok(blends.center.every((v,i)=>Math.abs(v-blends.reverse[i])<=2),'Blend is independent of light ordering');
 // A room's light cannot leak through its boundary.
 const room=await page.evaluate(async()=>{MapLighting.geometry([{id:'room',type:'building',x:-180,y:-160,w:360,h:320},{id:'lamp',type:'point_light',x:-300,y:-300,w:600,h:600,color:'#00ff00'}],{});await new Promise(r=>setTimeout(r,250));const c=document.querySelector('#mapPointLighting'),r=c.getBoundingClientRect(),m=document.querySelector('#map2Canvas').getScreenCTM(),sample=x=>[...c.getContext('2d').getImageData(Math.round((m.a*x+m.e-r.left)*c.width/r.width),Math.round((m.f-r.top)*c.height/r.height),1,1).data];return {inside:sample(0),outside:sample(215)};});assert.ok(room.inside[1]>room.inside[0]+50);assert.equal(room.outside[3],0,'Indoor lighting does not leak outdoors');
 await setup(24);await page.waitForTimeout(1000);await page.screenshot({path:path.join(__dirname,'artifacts/cached-fire-lights.png')});
 const firePixels=await page.evaluate(async()=>{const c=document.querySelector('#mapPointLighting'),sample=()=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let sum=0;for(let i=3;i<d.length;i+=64)sum+=d[i];return sum;},values=[];for(let i=0;i<5;i++){values.push(sample());await new Promise(r=>setTimeout(r,80));}return values;});assert.ok(new Set(firePixels).size>1,'Cached fire lights still visibly animate');
 const navigate=delta=>page.evaluate(async delta=>{const svg=document.querySelector('#map2Canvas'),c=document.querySelector('#mapPointLighting'),r=svg.getBoundingClientRect();let uncovered=0;for(let i=0;i<24;i++){svg.dispatchEvent(new WheelEvent('wheel',{deltaY:delta,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));await new Promise(requestAnimationFrame);const b=c.getBoundingClientRect();if(b.left>r.left+1||b.top>r.top+1||b.right<r.right-1||b.bottom<r.bottom-1)uncovered++;}return uncovered;},delta);
 assert.equal(await navigate(-100),0,'Zoom-in retains complete lighting coverage');await page.waitForTimeout(800);assert.equal(await page.locator('#mapPointLighting').getAttribute('data-shadow-resolution'),'192','Zoom restores detailed shadow silhouettes');
 assert.equal(await navigate(100),0,'Outdoor zoom-out retains complete lighting coverage');await page.waitForTimeout(350);
 await page.evaluate(()=>{Map2D.configure({nodes:[{id:'room',type:'building',x:-2200,y:-1800,w:4400,h:3600},{id:'lamp',type:'lantern',x:0,y:0,w:40,h:40,light_radius:600,fire_light:true}],players:[],edit:false,dm:true,canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});MapLighting.update({time:'Night'});});await page.waitForTimeout(400);assert.equal(await navigate(100),0,'Indoor zoom-out retains complete lighting coverage');
 const mobile=await browser.newContext({ignoreHTTPSErrors:true,isMobile:true,hasTouch:true,viewport:{width:844,height:390}});await mobile.request.post(base+'/api/login',{data:{username:'PartCardsQA',password:'Environment-QA-12345'}});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.stack));await mp.goto(base);await mp.locator('.campaign-row').filter({hasText:'Part Cards QA'}).click();await mp.locator('#map2Canvas').waitFor({state:'visible'});await mp.evaluate(()=>{Map2D.sync=()=>{};Map2D.configure({nodes:[{id:'mobile-fire',type:'lantern',x:0,y:0,w:30,h:30,light_radius:200,fire_light:true}],players:[],edit:false,dm:true,canvas:{grid:false},onChange:()=>{},onCanvasChange:()=>{}});MapLighting.update({time:'Night'});});await mp.waitForTimeout(700);const mobileSize=await mp.locator('#mapPointLighting').evaluate(c=>[c.width,c.height]);assert.ok(Math.max(...mobileSize)<=1024,'Mobile lighting stays within its buffer budget');await mobile.close();
 const fallback=await context.newPage();await fallback.goto(base);await fallback.evaluate(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind==='webgl2'?null:get.call(this,kind,...args);};});await fallback.addScriptTag({path:path.join(root,'site/map-light-compositor.js')});
 const fallbackResult=await fallback.evaluate(()=>{const base=document.createElement('canvas'),mask=document.createElement('canvas');base.width=mask.width=128;base.height=mask.height=128;const mc=mask.getContext('2d');mc.fillStyle='white';mc.fillRect(0,0,128,128);mc.fillStyle='black';mc.fillRect(64,0,64,128);const light={id:'fallback',key:'1',mask,rect:[0,0,128,128],center:[64,64],radius:64,power:1,softness:.5,color:[1,0,0]};MapLightCompositor.render(128,128,base,'base',[light]);let reads=0;const get=CanvasRenderingContext2D.prototype.getImageData;CanvasRenderingContext2D.prototype.getImageData=function(...args){reads++;return get.apply(this,args);};let c;try{for(let i=0;i<20;i++)c=MapLightCompositor.render(128,128,base,'base',[{...light,power:.8+i/100}]);}finally{CanvasRenderingContext2D.prototype.getImageData=get;}const ctx=c.getContext('2d');return {renderer:c.dataset.renderer,reads,lit:[...ctx.getImageData(50,64,1,1).data],shadow:[...ctx.getImageData(78,64,1,1).data]};});assert.equal(fallbackResult.renderer,'canvas');assert.equal(fallbackResult.reads,0);assert.ok(fallbackResult.lit[0]>200);assert.ok(fallbackResult.shadow[3]>30&&fallbackResult.shadow[0]===0,'Fallback preserves cast shadows even in daylight');await fallback.close();
 assert.deepEqual(errors,[]);console.log('PASS: cached animated fire shadows, constant resolution, zero animation readbacks, smooth saturated color blending, indoor confinement, zoom coverage and detail, mobile bounds, and cached canvas fallback.',{mobileSize,fallbackResult});
 }finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
