const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const base=process.env.REALM_PREVIEW_URL||'https://127.0.0.1:8774',c=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'});await c.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});let campaign=await(await c.request.post(base+'/api/work',{data:{title:'Equipment cards QA '+Date.now(),content:{category:'campaign',initial_map_kind:'2d'}}})).json();campaign=campaign.item||campaign;
 const records=(await(await c.request.get(base+'/api/work')).json()).items.filter(r=>r.content?.campaign_id===campaign.id),torch=records.find(r=>r.title==='Torch'),dagger=records.find(r=>r.title==='Dagger');assert.ok(torch&&dagger);
 const listing=await(await c.request.get(base+'/api/campaign/'+campaign.id+'/maps')).json(),url=base+'/api/campaign/'+campaign.id+'/maps/'+listing.active_map_id,map=await(await c.request.get(url)).json();const types=['npc','shop','encounter','chest','building','barrel'];const nodes=types.map((type,i)=>({id:type,type,x:-400+i*120,y:-60,w:80,h:80,label:type,contents:[]}));nodes.push({id:'legacy',type:'shop',x:0,y:180,w:80,h:80,label:'Legacy shop',contents:[{record_id:dagger.id,quantity:4,price_cp:25000}]},{id:'locked',type:'chest',x:180,y:180,w:80,h:80,label:'Locked chest',locked:true,contents:[{record_id:dagger.id,quantity:2}]});assert.ok((await c.request.put(url,{data:{revision:map.revision,state:{nodes}}})).ok());
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);await p.goto(base);await p.locator('.campaign-row').filter({hasText:campaign.title}).click();await p.locator('[data-map-mode=edit]').click();await p.locator('#map2ContentsPanel > summary').click();
 const saved=async()=> (await(await c.request.get(url)).json()).state.nodes;
 const saveAfter=async action=>{const response=p.waitForResponse(r=>r.url()===url&&r.request().method()==='PUT'&&r.status()===200);await action();await response;};
 for(const type of types){await p.locator('#map2Layers [data-layer-node='+type+']').click();const person=['npc','shop','encounter'].includes(type);assert.equal(await p.locator('#map2EquippedTitle').textContent(),person?'Equipped':'Stored items');await p.locator('#map2ContentsSearch').fill('Torch');assert.equal(await p.locator('#map2ContentsChoices input').count(),0);assert.equal(await p.locator('#map2ContentsChoices .map-content-card img').count(),1);assert.equal(await p.locator('#map2Equipped input[aria-label$="price in gold"]').count(),0);
 await saveAfter(()=>p.locator('#map2ContentsChoices').getByRole('button',{name:(person?'Equip ':'Add ')+'Torch',exact:true}).click());assert.equal(await p.locator('#map2Equipped .map-equipped-card').count(),1);assert.equal(await p.locator('#map2ContentsChoices .map-content-card').count(),0);assert.equal(await p.locator('#map2Equipped input[aria-label$="price in gold"]').count(),person?1:0);
 await saveAfter(async()=>{const q=p.getByRole('spinbutton',{name:'Torch quantity',exact:true});await q.fill('3');await q.press('Tab');});if(person)await saveAfter(async()=>{const price=p.getByRole('spinbutton',{name:'Torch price in gold',exact:true});await price.fill('1.2345');await price.press('Tab');});let part=(await saved()).find(n=>n.id===type);assert.equal(part.contents[0].quantity,3);if(person)assert.equal(part.contents[0].price_cp,12345);
 if(type==='shop'){for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [1440,390]){await p.setViewportSize({width,height:1000});const card=p.locator('#map2Equipped .map-equipped-card');await card.scrollIntoViewIfNeeded();assert.ok(await card.evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:'tests/artifacts/equipped-'+theme+'-'+width+'.png'});}}await p.setViewportSize({width:1440,height:1000});}
 await saveAfter(()=>p.locator('#map2Equipped').getByRole('button',{name:(person?'Unequip ':'Remove ')+'Torch',exact:true}).click());assert.equal((await saved()).find(n=>n.id===type).contents.length,0);assert.equal(await p.locator('#map2ContentsChoices .map-content-card').count(),1);
 console.log('PASS card add, quantity, price visibility, removal and save:',type);
 }
 await p.locator('#map2Layers [data-layer-node=legacy]').click();assert.equal(await p.getByRole('spinbutton',{name:'Dagger quantity',exact:true}).inputValue(),'4');assert.equal(await p.getByRole('spinbutton',{name:'Dagger price in gold',exact:true}).inputValue(),'2.5');assert.equal(await p.locator('#map2Equipped .map-equipped-card').count(),1);await p.locator('#map2Equipped').getByRole('button',{name:'View Dagger',exact:true}).click();await p.locator('#recordDetailModal').waitFor({state:'visible'});await p.locator('#recordDetailModal [data-bs-dismiss]').first().click();await p.locator('#recordDetailModal').waitFor({state:'hidden'});
 await saveAfter(()=>p.getByRole('button',{name:'Unequip Dagger',exact:true}).click());await saveAfter(()=>p.locator('#map2Canvas').press('Control+z'));assert.equal(await p.getByRole('spinbutton',{name:'Dagger price in gold',exact:true}).inputValue(),'2.5');
 await p.locator('#map2Layers [data-layer-node=locked]').click();assert.equal(await p.getByRole('button',{name:'Remove Dagger',exact:true}).isDisabled(),true);assert.equal(await p.getByRole('spinbutton',{name:'Dagger quantity',exact:true}).isDisabled(),true);await p.locator('#map2ContentsSearch').fill('Torch');assert.equal(await p.getByRole('button',{name:'Add Torch',exact:true}).isDisabled(),true);
 await p.reload();await p.locator('.campaign-row').filter({hasText:campaign.title}).click();await p.locator('[data-map-mode=edit]').click();await p.locator('#map2Layers [data-layer-node=legacy]').click();await p.locator('#map2ContentsPanel > summary').click();assert.equal(await p.getByRole('spinbutton',{name:'Dagger quantity',exact:true}).inputValue(),'4');assert.equal(await p.getByRole('spinbutton',{name:'Dagger price in gold',exact:true}).inputValue(),'2.5');assert.deepEqual(errors,[]);console.log('PASS legacy contents/prices, detail cards, undo, locked parts, reload, both themes and narrow layouts');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
