const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const base=process.env.MAP_TEST_BASE||'https://127.0.0.1:8773',c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1050},reducedMotion:'reduce'});await c.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});let campaign=await(await c.request.post(base+'/api/work',{data:{title:'Select and pan QA '+Date.now(),content:{category:'campaign',initial_map_kind:'2d'}}})).json();campaign=campaign.item||campaign;const list=await(await c.request.get(base+'/api/campaign/'+campaign.id+'/maps')).json(),url=base+'/api/campaign/'+campaign.id+'/maps/'+list.active_map_id,map=await(await c.request.get(url)).json();const nodes=[{id:'a',type:'building',x:-340,y:-120,w:160,h:160,floor_texture:'wood',wall_texture:'stone',rotation:0},{id:'b',type:'building',x:160,y:-120,w:160,h:160,floor_texture:'wood',wall_texture:'stone',rotation:0},{id:'locked',type:'building',x:160,y:220,w:160,h:160,floor_texture:'wood',wall_texture:'stone',rotation:0,locked:true}];assert.ok((await c.request.put(url,{data:{revision:map.revision,state:{nodes}}})).ok());
const p=await c.newPage(),errors=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));let saves=0;p.on('request',r=>{if(r.url()===url&&r.method()==='PUT')saves++;});await p.goto(base);await p.locator('.campaign-row').filter({hasText:campaign.title}).click();await p.locator('[data-map-mode=edit]').click();await p.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();await p.locator('[data-map2-tool=select]').click();const svg=p.locator('#map2Canvas');
const point=async(x,y)=>p.evaluate(([x,y])=>{const q=new DOMPoint(x,y).matrixTransform(document.querySelector('#map2Canvas').getScreenCTM());return{x:q.x,y:q.y};},[x,y]);
async function click(x,y){const q=await point(x,y);await p.mouse.click(q.x,q.y);}
async function drag(x,y,dx,dy){const q=await point(x,y);await p.mouse.move(q.x,q.y);await p.mouse.down();await p.mouse.move(q.x+dx,q.y+dy,{steps:8});await p.mouse.up();}
const positions=async()=>{const saved=await(await c.request.get(url)).json();return saved.state.nodes.map(n=>({id:n.id,x:n.x,y:n.y,w:n.w,h:n.h}));};const original=await positions();
const saveAfter=async(action)=>{const response=p.waitForResponse(r=>r.url()===url&&r.request().method()==='PUT'&&r.status()===200);await action();await response;};
let view=await svg.getAttribute('viewBox');await drag(-260,-40,75,45);assert.notEqual(await svg.getAttribute('viewBox'),view);assert.deepEqual(await positions(),original);assert.equal(saves,0);assert.equal(await p.locator('#map2Layers button.active').count(),0);
await click(-260,-40);assert.equal(await p.locator('#map2Layers [data-layer-node=a]').getAttribute('class'),'map2-layer-row active');await drag(-260,-40,2,1);assert.deepEqual(await positions(),original);assert.equal(saves,0);
view=await svg.getAttribute('viewBox');await saveAfter(()=>drag(-260,-40,65,35));assert.equal(await svg.getAttribute('viewBox'),view);assert.notDeepEqual(await positions(),original);await saveAfter(()=>p.keyboard.press('Control+z'));assert.deepEqual(await positions(),original);
await svg.focus();await p.keyboard.press('Escape');await click(-260,-40);const selectedBefore=await p.locator('#map2Layers button.active').count();view=await svg.getAttribute('viewBox');await drag(240,-40,-45,50);assert.notEqual(await svg.getAttribute('viewBox'),view);assert.deepEqual(await positions(),original);assert.equal(await p.locator('#map2Layers button.active').count(),selectedBefore);
view=await svg.getAttribute('viewBox');await drag(-450,260,40,-35);assert.notEqual(await svg.getAttribute('viewBox'),view);assert.deepEqual(await positions(),original);await click(-450,260);assert.equal(await p.locator('#map2Layers button.active').count(),0);
await click(-260,-40);await p.keyboard.down('Shift');await click(240,-40);await p.keyboard.up('Shift');assert.equal(await p.locator('#map2Layers button.active').count(),2);await saveAfter(()=>drag(-260,-40,50,35));const group=await positions();assert.equal(group[0].x-original[0].x,group[1].x-original[1].x);assert.equal(group[0].y-original[0].y,group[1].y-original[1].y);await saveAfter(()=>p.keyboard.press('Control+z'));assert.deepEqual(await positions(),original);
await svg.focus();await p.keyboard.press('Escape');await click(240,300);view=await svg.getAttribute('viewBox');await drag(240,300,-35,-30);assert.notEqual(await svg.getAttribute('viewBox'),view);assert.deepEqual(await positions(),original);
await svg.focus();await p.keyboard.press('Escape');await click(-260,-40);const q=await point(240,-40);await p.mouse.move(q.x,q.y);await p.mouse.down();await p.evaluate(()=>document.querySelector('#map2Canvas').dispatchEvent(new PointerEvent('pointercancel',{pointerId:1,bubbles:true})));await p.mouse.up();assert.equal(await p.locator('#map2Layers [data-layer-node=a]').getAttribute('class'),'map2-layer-row active');assert.deepEqual(await positions(),original);
await svg.focus();await p.keyboard.press('Escape');view=await svg.getAttribute('viewBox');const beforeBoxSaves=saves,start=await point(-260,-40),finish=await point(350,400);await p.keyboard.down('Shift');await p.mouse.move(start.x,start.y);await p.mouse.down();await p.mouse.move(finish.x,finish.y,{steps:8});await p.mouse.up();await p.keyboard.up('Shift');assert.equal(await svg.getAttribute('viewBox'),view,'Shift-drag over a part never pans');assert.deepEqual(await positions(),original,'Shift-drag never moves a part');assert.equal(saves,beforeBoxSaves,'Selection does not save map geometry');assert.ok((await p.locator('#map2Layers [data-layer-node=locked]').getAttribute('class')).includes('active'),'Shift-drag starting on a part selects objects inside the box');
assert.deepEqual(errors,[]);console.log('PASS unselected/background drag pans; click selects; selected/group drag moves; jitter and cancellation preserve data; undo and locked parts work');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
