const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1500,height:1000}}),base='https://127.0.0.1:8766';await c.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});
const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator('#newCampaignButton').click();await p.locator('[name=initial_map_kind]').selectOption('2d');await p.locator('#workForm [name=title]').fill('Starting 2D QA');await p.locator('#workForm button[type=submit]').click();await p.locator('#workModal').waitFor({state:'hidden'});await p.locator('.campaign-row').filter({hasText:'Starting 2D QA'}).click();await p.locator('#map2Canvas').waitFor({state:'visible'});
await p.locator('[data-map-mode=edit]').click();await p.locator('[data-map2-tool=water]').click();const r=await p.locator('#map2Canvas').boundingBox();await p.mouse.move(r.x+r.width*.4,r.y+r.height*.4);await p.mouse.down();await p.mouse.move(r.x+r.width*.6,r.y+r.height*.6);await p.mouse.up();await p.waitForTimeout(1200);assert.equal(await p.locator('#map2Layers button').count(),1);await p.locator('[data-map2-action=undo]').click();assert.equal(await p.locator('#map2Layers button').count(),0);await p.locator('[data-map2-action=redo]').click();assert.equal(await p.locator('#map2Layers button').count(),1);
await p.locator('[data-map-mode=story]').click();await p.locator('[data-scene=location]').fill('North gate');await p.locator('[data-scene=location]').press('Tab');await p.locator('#mapStoryDiceToggle').click();await p.locator('#railDie').click();assert.match(await p.locator('#railDieResult').textContent(),/Total/);await p.locator('#mapStoryDiceToggle').click();
await p.locator('#mapNewToggle').click();await p.locator('#mapNewForm [name=title]').fill('Second 3D');await p.locator('#mapNewForm [name=kind]').selectOption('3d');await p.locator('#mapNewForm button[type=submit]').click();await p.locator('#mapPlaceholder').waitFor({state:'visible'});assert.equal(await p.locator('#mapWorkspaceSelect option').count(),2);const first=await p.locator('#mapWorkspaceSelect option').first().getAttribute('value');await p.locator('#mapWorkspaceSelect').selectOption(first);await p.locator('#map2Canvas').waitFor({state:'visible'});assert.equal(await p.locator('[data-scene=location]').inputValue(),'North gate');assert.equal(await p.locator('#map2Layers button').count(),1);
await p.reload();await p.locator('.campaign-row').filter({hasText:'Starting 2D QA'}).click();await p.locator('#map2Canvas').waitFor({state:'visible'});assert.equal(await p.locator('[data-scene=location]').inputValue(),'North gate');await p.locator('[data-map-mode=edit]').click();await p.locator('#campaignDashboard').screenshot({path:'tests/artifacts/maps-2d.png'});assert.deepEqual(errors,[]);console.log('PASS: starting 2D, editing, undo/redo, scene, DM dice, multiple map types and persistence.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
