const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const base='https://127.0.0.1:8774',dm=await b.newContext({ignoreHTTPSErrors:true}),pc=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'});for(const[c,name]of[[dm,'TabletopQA'],[pc,'DicePlayerQA']])await c.request.post(base+'/api/login',{data:{username:name,password:'Tabletop-QA-12345'}});const p=await pc.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
const openCard=async(panel,title)=>{await p.locator(panel).getByRole('button',{name:'View '+title,exact:true}).click();await p.locator('#recordDetailModal').waitFor({state:'visible'});assert.equal(await p.locator('#detailTitle').textContent(),title);assert.ok(await p.locator('#recordDetailModal').evaluate(e=>{const title=e.querySelector('#detailTitle'),r=title.getBoundingClientRect(),top=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return e.contains(top);}), 'Dialog must be visible above fullscreen map');await p.locator('#recordDetailModal [data-bs-dismiss]').first().click();await p.locator('#recordDetailModal').waitFor({state:'hidden'});};
for(const kind of ['Normal','AI']){const records=(await(await dm.request.get(base+'/api/work')).json()).items,camp=records.find(r=>r.title==='Dice QA '+kind),char=records.find(r=>r.title==='Elara'&&r.content.campaign_id===camp.id);for(const[title,key]of[['Dagger','owner_ids'],['Cure Wounds','user_ids'],['Dash','user_ids']]){const r=records.find(r=>r.title===title&&r.content.campaign_id===camp.id);await dm.request.put(base+'/api/work/'+r.id,{data:{title:r.title,content:{...r.content,[key]:[char.id],reference_only:false,grant_mode:'characters'}}});}await p.goto(base);await p.locator('.campaign-row').filter({hasText:camp.title}).click();if(kind==='AI'){await p.locator('#aiSpeakerButton').click();await p.locator('#aiSpeakerMenu button').filter({hasText:'Elara'}).click();}
await p.locator('#inventoryPreview .equipment-item .record-card').waitFor({state:'visible'});assert.equal(await p.locator('#inventoryPreview .record-card img').count(),1);assert.equal(await p.locator('#attackPreview .record-card img').count(),2);
for(const[panel,title]of[['#inventoryPreview','Dagger'],['#attackPreview','Cure Wounds'],['#attackPreview','Dash']])await openCard(panel,title);
const dagger=p.locator('#inventoryPreview .equipment-item').filter({hasText:'Dagger'});if(await dagger.getByRole('button',{name:'Unequip Dagger',exact:true}).count()){await dagger.getByRole('button',{name:'Unequip Dagger',exact:true}).click();await p.locator('[data-equipment-group=inventory] .equipment-item').filter({hasText:'Dagger'}).waitFor();}
await dagger.getByRole('button',{name:'Equip',exact:true}).click();await p.locator('#inventoryPreview [data-equipment-group=equipped] .equipment-item').filter({hasText:'Dagger'}).waitFor();await dagger.getByRole('button',{name:'Unequip Dagger',exact:true}).click();await p.locator('#inventoryPreview [data-equipment-group=inventory] .equipment-item').filter({hasText:'Dagger'}).waitFor();
if(kind==='Normal'){for(const fallback of [false,true]){if(fallback)await p.evaluate(()=>HTMLElement.prototype.requestFullscreen=()=>Promise.reject(new Error('QA fallback')));await p.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();await p.waitForFunction(()=>document.querySelector('#campaignDashboard').classList.contains('map-workspace-fullscreen'));for(const[panel,title]of[['#inventoryPreview','Dagger'],['#attackPreview','Cure Wounds'],['#attackPreview','Dash']])await openCard(panel,title);await p.locator('#mapFullscreenBar [data-map-fullscreen]').click();await p.waitForFunction(()=>!document.querySelector('#campaignDashboard').classList.contains('map-workspace-fullscreen'));}}
for(const theme of ['light','dark'])for(const width of [1440,390]){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.setViewportSize({width,height:1000});assert.ok(await p.locator('#inventoryPreview').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.ok(await p.locator('#attackPreview').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await openCard('#attackPreview','Dash');await p.locator('#inventoryPreview').scrollIntoViewIfNeeded();await p.screenshot({path:'tests/artifacts/player-cards-'+kind+'-'+theme+'-'+width+'.png'});}await p.setViewportSize({width:1440,height:1000});console.log('PASS player inventory, equip/unequip, ability/spell details and responsive cards:',kind);
}assert.deepEqual(errors,[]);console.log('PASS native and fallback fullscreen card dialogs, both themes, desktop/mobile, Normal/AI characters');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
