const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const base=process.env.REALM_PREVIEW_URL||'https://127.0.0.1:8772',ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1050},reducedMotion:'reduce'});await ctx.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});
 const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(8000);await p.goto(base);await p.locator('.campaign-row').filter({hasText:'Dice QA Normal'}).click();
 const handle=(root,side)=>p.locator(root+' > .realm-splitter[data-resize-side='+side+']');
 async function drag(root,side,delta){const h=handle(root,side);await h.scrollIntoViewIfNeeded();const box=await h.boundingBox();assert.ok(box);const x=box.x+box.width/2,y=box.y+box.height/2;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+(side==='height'?0:delta),y+(side==='height'?delta:0),{steps:8});await p.mouse.up();}
 const value=async(root,side)=>{await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return Number(await handle(root,side).getAttribute('aria-valuenow'));};
 await handle('#campaignDashboard','left').waitFor({state:'visible'});const initial=await value('#campaignDashboard','left');await drag('#campaignDashboard','left',70);assert.ok(await value('#campaignDashboard','left')>=initial+65);
 await p.evaluate(()=>{window.resizeKeyLeaked=false;document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')window.resizeKeyLeaked=true;},{once:true});});await handle('#campaignDashboard','right').focus();const right=await value('#campaignDashboard','right');await p.keyboard.press('ArrowLeft');assert.equal(await value('#campaignDashboard','right'),right+10);assert.equal(await p.evaluate(()=>window.resizeKeyLeaked),false,'Resizing must not trigger map shortcuts');
 const height=await value('#campaignDashboard','height');await drag('#campaignDashboard','height',80);assert.ok(await value('#campaignDashboard','height')>=height+75);
 const stored=await value('#campaignDashboard','left');await p.reload();await p.locator('.campaign-row').filter({hasText:'Dice QA Normal'}).click();await handle('#campaignDashboard','left').waitFor({state:'visible'});assert.equal(await value('#campaignDashboard','left'),stored);
 for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.locator('#campaignDashboard').scrollIntoViewIfNeeded();await p.screenshot({path:'tests/artifacts/realm-resize-'+theme+'.png'});}
 await p.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();await handle('#campaignDashboard','left').waitFor({state:'visible'});const full=await value('#campaignDashboard','left');await drag('#campaignDashboard','left',40);assert.ok(await value('#campaignDashboard','left')>=full+35);await p.locator('#mapLeftPanelToggle').click();await handle('#campaignDashboard','left').waitFor({state:'hidden'});await p.locator('#mapLeftPanelToggle').click();await handle('#campaignDashboard','left').waitFor({state:'visible'});await p.locator('#mapFullscreenBar [data-map-fullscreen]').click();assert.equal(await value('#campaignDashboard','left'),stored);
 await drag('#campaignDashboard','left',1600);assert.ok((await p.locator('.map-stage').boundingBox()).width>=319);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await handle('#campaignDashboard','left').dblclick();assert.equal(await value('#campaignDashboard','left'),initial);
 await p.locator('#realmMenuButton').click();await p.locator('#realmSidebar [data-record-type=item]').click();assert.equal(await handle('#campaignDashboard','left').isVisible(),false);
 for(const [button,root] of [['#artAtelierButton','#aaEditor'],['#spellAtelierButton','#spellAtelier']]){await p.locator('#realmMenuButton').click();await p.locator(button).click();await handle(root,'left').waitFor({state:'visible'}).catch(async e=>{console.log(await p.evaluate(root=>({fullscreen:document.fullscreenElement?.id,root:document.querySelector(root)?.outerHTML.slice(0,350),grid:getComputedStyle(document.querySelector(root)).gridTemplateColumns,rect:document.querySelector(root).getBoundingClientRect().toJSON(),center:document.querySelector(root+' .aa-canvas-panel')?.getBoundingClientRect().toJSON()}),root));throw e;});const old=await value(root,'left');await drag(root,'left',45);assert.ok(await value(root,'left')>=old+40);await handle(root,'left').focus();await p.keyboard.press('Home');await p.waitForFunction(({root,old})=>Number(document.querySelector(root+' > [data-resize-side=left]').getAttribute('aria-valuenow'))===old,{root,old});const h=await value(root,'height');await drag(root,'height',40);assert.ok(await value(root,'height')>=h+35);}
 await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>![...document.querySelectorAll('.realm-splitter')].some(e=>e.getClientRects().length));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 const touch=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1050},isMobile:true,hasTouch:true});await touch.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});const t=await touch.newPage();await t.goto(base);await t.locator('.campaign-row').filter({hasText:'Dice QA Normal'}).click();assert.equal(await t.locator('.realm-splitter:visible').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS desktop dragging, keyboard adjustment, reset, height, persistence, fullscreen collapse/restore, archive transitions, art/spell workspaces, mobile and touch exclusion');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
