const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const base='https://127.0.0.1:8771',c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'});await c.request.post(base+'/api/login',{data:{username:'TabletopQA',password:'Tabletop-QA-12345'}});const response=await c.request.post(base+'/api/work',{data:{title:'Merchant layout QA '+Date.now(),content:{category:'campaign',initial_map_kind:'2d'}}});const created=await response.json();const campaign=created.item||created;assert.ok(campaign.id,JSON.stringify(created));await c.request.post(base+'/api/work',{data:{title:'Merchant customer',content:{category:'character',campaign_id:campaign.id,tabletop:{money_cp:100000}}}});
 const p=await c.newPage();p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator('.campaign-row').filter({hasText:campaign.title}).click();await p.locator('#map2Canvas').waitFor({state:'visible'});
 const list=await(await c.request.get(base+'/api/campaign/'+campaign.id+'/maps')).json(),mid=list.active_map_id,map=await(await c.request.get(base+'/api/campaign/'+campaign.id+'/maps/'+mid)).json();
 await c.request.put(base+'/api/campaign/'+campaign.id+'/maps/'+mid,{data:{revision:map.revision,state:{nodes:[{id:'merchant-layout',type:'shop',name:'Golden Griffin',x:140,y:100,w:80,h:80,money_cp:50600,contents_public:true,contents:[]}]}}});
 await p.reload();await p.locator('.campaign-row').filter({hasText:campaign.title}).click();await p.locator('[data-node="merchant-layout"]').click();
 for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [1440,768,390]){await p.setViewportSize({width,height:1000});const popup=p.locator('#map2ObjectPopup');await popup.scrollIntoViewIfNeeded();assert.ok(await popup.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Trade horizontal overflow');assert.ok((await popup.boundingBox()).width>=300,'Trade width');await p.screenshot({path:`tests/artifacts/realm-panels/merchant-${theme}-${width}.png`});}}
 const editor=p.locator('.map-wallet-editor').first();await editor.locator('summary').click();await editor.getByRole('spinbutton',{name:'Merchant holds gold'}).fill('7');await editor.getByRole('button',{name:'Set money'}).click();await p.waitForFunction(()=>document.querySelector('.map-trade-wallet .coin-balance')?.textContent.replace(',','.').includes('7.06'));
 await p.locator('#mapWorkspaceHeader [data-map-fullscreen]').click();await p.locator('#mapLeftPanelToggle').click();assert.ok(await p.locator('#map2ObjectPopup').isVisible());await p.locator('#map2ClosePopup').click();await p.locator('#mapFullscreenBar [data-map-fullscreen]').click();await p.setViewportSize({width:1440,height:1000});await p.locator('[data-map-mode=edit]').click();await p.locator('[data-node="merchant-layout"]').click();await p.locator('#map2ContentsPanel > summary').click();await p.locator('#map2ContentsSearch').fill('Torch');
 await p.locator('#map2ContentsChoices .map-content-card').first().click();const stock=p.locator('#map2Equipped .map-equipped-card').first();await stock.getByRole('spinbutton',{name:/quantity/}).fill('3');await stock.getByRole('spinbutton',{name:/quantity/}).press('Tab');await stock.getByRole('spinbutton',{name:/price in gold/}).fill('0.0001');await stock.getByRole('spinbutton',{name:/price in gold/}).press('Tab');
 for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [1440,1000,768,390]){await p.setViewportSize({width,height:1000});await stock.scrollIntoViewIfNeeded();assert.ok(await stock.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Stock row overflow');assert.ok(await stock.locator('.rail-entry-copy strong').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=14));assert.ok(await stock.getByRole('spinbutton',{name:/price in gold/}).evaluate(e=>e.clientWidth>=110),'Price field width');await p.screenshot({path:'tests/artifacts/realm-panels/stock-'+theme+'-'+width+'.png'});}}
 const savedMap=await(await c.request.get(base+'/api/campaign/'+campaign.id+'/maps/'+mid)).json();assert.equal(savedMap.state.nodes.find(n=>n.id==='merchant-layout').contents[0].quantity,3);assert.equal(savedMap.state.nodes.find(n=>n.id==='merchant-layout').contents[0].price_cp,1);
 assert.deepEqual(errors,[]);console.log('PASS merchant layout in both themes at 3 widths, wallet save persistence, fullscreen and close');
 await c.request.put(base+'/api/work/'+campaign.id,{data:{title:campaign.title,content:campaign.content}});
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
