const {chromium}=require('C:/Users/eric_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.route('https://spell.test/',route=>route.fulfill({contentType:'text/html',body:'<main id="campaignDashboard"></main>'}));
  await page.goto('https://spell.test/');
  await page.addStyleTag({path:'site/spell-atelier.css'});
  for(const file of ['spell-symbols','spell-engine','spell-equations','spell-preview','spell-atelier'])await page.addScriptTag({path:'site/'+file+'.js'});
  await page.evaluate(()=>SpellAtelier.setActive(true,1,1));
  await page.locator('[data-example="fire:levitation"]').click();
  await page.locator('#saCast').click();await page.locator('#saPreviewLoop').check();
  const count=await page.locator('#saDrawing .sa-node').count();
  await page.locator('#saFullscreen').click();
  await page.waitForFunction(()=>document.fullscreenElement?.id==='saCanvasFrame');
  assert.equal(await page.locator('#saFullscreen').innerText(),'Exit fullscreen');
  assert.ok((await page.locator('#spellAtelierCanvas').boundingBox()).height>700);
  for(const id of ['saCast','saStop','saPreviewTime','saPreviewDuration','saPreviewSpeed','saPreviewLoop'])assert.ok(await page.locator('#saFullscreenPreview #'+id).isVisible(),id);
  await page.locator('#saStop').click();assert.equal(await page.locator('#saFullscreenPreview #saPreviewTime').count(),0);
  await page.locator('#saCast').click();assert.ok(await page.locator('#saFullscreenPreview #saPreviewTime').isVisible());
  assert.equal(await page.locator('#saDrawing .sa-node').count(),count);
  assert.ok(await page.locator('#saEffects circle').count()>0);
  await page.locator('#saFullscreen').click();await page.waitForFunction(()=>!document.fullscreenElement);
  assert.ok(await page.locator('#saPreviewMath #saPreviewControls').isVisible());
  await page.evaluate(()=>document.getElementById('saCanvasFrame').requestFullscreen=undefined);
  await page.locator('#saFullscreen').click();assert.ok(await page.locator('#saCanvasFrame').evaluate(e=>e.classList.contains('sa-expanded')));
  await page.keyboard.press('Escape');assert.equal(await page.locator('#saFullscreen').getAttribute('aria-pressed'),'false');
  await page.clock.install();await page.clock.pauseAt(new Date());
  await page.locator('#saPreviewDuration').fill('20');await page.locator('#saPreviewDuration').press('Tab');
  assert.equal(await page.locator('#saPreviewTime').getAttribute('max'),'20');
  await page.locator('#saPreviewSpeed').selectOption('2');
  await page.evaluate(()=>{const t=document.getElementById('saPreviewTime');t.value=0;t.dispatchEvent(new Event('input'));});
  await page.locator('#saPreviewPause').click();await page.clock.runFor(500);
  let elapsed=Number(await page.locator('#saPreviewTime').inputValue());assert.ok(elapsed>.9&&elapsed<1.1,elapsed);
  await page.locator('#saPreviewDuration').fill('2');await page.locator('#saPreviewDuration').press('Tab');
  await page.locator('#saPreviewLoop').uncheck();await page.clock.runFor(1000);
  assert.equal(Number(await page.locator('#saPreviewTime').inputValue()),2);
  assert.equal(await page.locator('#saPreviewPause').innerText(),'Play');
  await page.locator('#saPreviewLoop').check();await page.locator('#saPreviewPause').click();await page.clock.runFor(1250);
  elapsed=Number(await page.locator('#saPreviewTime').inputValue());assert.ok(elapsed>.4&&elapsed<.6,elapsed);
  await page.locator('#saPreviewDuration').fill('0');await page.locator('#saPreviewDuration').press('Tab');
  assert.equal(await page.locator('#saPreviewDuration').inputValue(),'0.5');
  await page.locator('#saPreviewDuration').fill('1200');await page.locator('#saPreviewDuration').press('Tab');
  assert.equal(await page.locator('#saPreviewTime').getAttribute('max'),'1200');
  await page.locator('#saPreviewSpeed').selectOption('10');
  await page.evaluate(()=>{const t=document.getElementById('saPreviewTime');t.value=1200;t.dispatchEvent(new Event('input'));});
  assert.equal(await page.locator('#saPreviewClock').innerText(),'1200.00 s');
  assert.doesNotMatch(await page.locator('#saEffects').innerHTML(),/NaN|Infinity/);
  await page.locator('#saCast').click();
  assert.ok(await page.locator('#saEffectLabel').isVisible());
  await page.clock.runFor(4900);assert.ok(await page.locator('#saEffectLabel').isVisible());
  await page.clock.runFor(150);assert.equal(await page.locator('#saEffectLabel').isVisible(),false);
  await page.evaluate(()=>document.getElementById('saCast').click());await page.clock.runFor(3000);
  await page.evaluate(()=>document.getElementById('saCast').click());await page.clock.runFor(2500);
  assert.ok(await page.locator('#saEffectLabel').isVisible());
  await page.clock.runFor(2600);assert.equal(await page.locator('#saEffectLabel').isVisible(),false);
  assert.deepEqual(errors,[]);console.log('Fullscreen, duration, playback speed, stopping and looping at the chosen duration passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

